*** Starting uWSGI 2.0.11.1 (32bit) on [Sun Dec 27 09:53:37 2015] ***
compiled with version: 4.1.2 20080704 (Red Hat 4.1.2-55) on 16 August 2015 12:55:34
os: Linux-2.6.18-371.1.2.el5 #1 SMP Tue Oct 22 12:57:43 EDT 2013
nodename: centos5.5_32
machine: i686
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /xgb/xueer
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 48491
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:5050 fd 3
Python version: 2.7.9 (default, Mar 22 2015, 19:48:42)  [GCC 4.1.2 20080704 (Red Hat 4.1.2-55)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x840da68
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 383928 bytes (374 KB) for 5 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./wsgi.py", line 3, in <module>
    from manage import app
  File "./manage.py", line 7, in <module>
    from flask_migrate import Migrate, MigrateCommand
ImportError: No module named flask_migrate
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1288)
spawned uWSGI worker 1 (pid: 1291, cores: 1)
spawned uWSGI worker 2 (pid: 1292, cores: 1)
spawned uWSGI worker 3 (pid: 1293, cores: 1)
spawned uWSGI worker 4 (pid: 1294, cores: 1)
spawned uWSGI worker 5 (pid: 1295, cores: 1)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.11.1 (32bit) on [Sun Dec 27 09:53:48 2015] ***
compiled with version: 4.1.2 20080704 (Red Hat 4.1.2-55) on 16 August 2015 12:55:34
os: Linux-2.6.18-371.1.2.el5 #1 SMP Tue Oct 22 12:57:43 EDT 2013
nodename: centos5.5_32
machine: i686
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /xgb/xueer
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 48491
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:5050 fd 3
Python version: 2.7.9 (default, Mar 22 2015, 19:48:42)  [GCC 4.1.2 20080704 (Red Hat 4.1.2-55)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xa1c9a68
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 383928 bytes (374 KB) for 5 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./wsgi.py", line 3, in <module>
    from manage import app
  File "./manage.py", line 7, in <module>
    from flask_migrate import Migrate, MigrateCommand
ImportError: No module named flask_migrate
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1296)
spawned uWSGI worker 1 (pid: 1299, cores: 1)
spawned uWSGI worker 2 (pid: 1300, cores: 1)
spawned uWSGI worker 3 (pid: 1301, cores: 1)
spawned uWSGI worker 4 (pid: 1302, cores: 1)
spawned uWSGI worker 5 (pid: 1303, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 1303|app: -1|req: -1/1] 202.114.44.210 () {34 vars in 435 bytes} [Sun Dec 27 09:55:44 2015] GET /api/v1.0/courses/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1303|app: -1|req: -1/2] 202.114.44.210 () {34 vars in 435 bytes} [Sun Dec 27 09:55:48 2015] GET /api/v1.0/courses/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 1303|app: -1|req: -1/3] 202.114.44.210 () {34 vars in 435 bytes} [Sun Dec 27 09:55:56 2015] GET /api/v1.0/courses/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 2 buried after 0 seconds
worker 1 buried after 0 seconds
worker 3 buried after 0 seconds
worker 4 buried after 0 seconds
worker 5 buried after 0 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.11.1 (32bit) on [Sun Dec 27 09:59:58 2015] ***
compiled with version: 4.1.2 20080704 (Red Hat 4.1.2-55) on 16 August 2015 12:55:34
os: Linux-2.6.18-371.1.2.el5 #1 SMP Tue Oct 22 12:57:43 EDT 2013
nodename: centos5.5_32
machine: i686
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /xgb/xueer
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 48491
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:5050 fd 3
Python version: 2.7.9 (default, Mar 22 2015, 19:48:42)  [GCC 4.1.2 20080704 (Red Hat 4.1.2-55)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x8cd0a68
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 383928 bytes (374 KB) for 5 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./wsgi.py", line 3, in <module>
    from manage import app
  File "./manage.py", line 7, in <module>
    from flask_migrate import Migrate, MigrateCommand
ImportError: No module named flask_migrate
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1345)
spawned uWSGI worker 1 (pid: 1348, cores: 1)
spawned uWSGI worker 2 (pid: 1349, cores: 1)
spawned uWSGI worker 3 (pid: 1350, cores: 1)
spawned uWSGI worker 4 (pid: 1351, cores: 1)
spawned uWSGI worker 5 (pid: 1352, cores: 1)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 0 seconds
worker 2 buried after 0 seconds
worker 3 buried after 0 seconds
worker 4 buried after 0 seconds
worker 5 buried after 0 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.11.1 (32bit) on [Sun Dec 27 10:00:08 2015] ***
compiled with version: 4.1.2 20080704 (Red Hat 4.1.2-55) on 16 August 2015 12:55:34
os: Linux-2.6.18-371.1.2.el5 #1 SMP Tue Oct 22 12:57:43 EDT 2013
nodename: centos5.5_32
machine: i686
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /xgb/xueer
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 48491
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:5050 fd 3
Python version: 2.7.9 (default, Mar 22 2015, 19:48:42)  [GCC 4.1.2 20080704 (Red Hat 4.1.2-55)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x8d6fa68
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 383928 bytes (374 KB) for 5 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./wsgi.py", line 3, in <module>
    from manage import app
  File "./manage.py", line 7, in <module>
    from flask_migrate import Migrate, MigrateCommand
ImportError: No module named flask_migrate
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1353)
spawned uWSGI worker 1 (pid: 1356, cores: 1)
spawned uWSGI worker 2 (pid: 1357, cores: 1)
spawned uWSGI worker 3 (pid: 1358, cores: 1)
spawned uWSGI worker 4 (pid: 1359, cores: 1)
spawned uWSGI worker 5 (pid: 1360, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 1360|app: -1|req: -1/1] 202.114.44.210 () {34 vars in 432 bytes} [Sun Dec 27 10:00:20 2015] GET /api/v1.0/courses/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.11.1 (32bit) on [Sun Dec 27 10:04:16 2015] ***
compiled with version: 4.1.2 20080704 (Red Hat 4.1.2-55) on 16 August 2015 12:55:34
os: Linux-2.6.18-371.1.2.el5 #1 SMP Tue Oct 22 12:57:43 EDT 2013
nodename: centos5.5_32
machine: i686
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /xgb/xueer
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 48491
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:5050).
bind(): Address already in use [core/socket.c line 764]
--- no python application found, check your startup logs for errors ---
[pid: 1360|app: -1|req: -1/2] 202.114.44.210 () {34 vars in 432 bytes} [Sun Dec 27 10:04:23 2015] GET /api/v1.0/courses/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
